language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
install:
  - yarn --pure-lockfile
  - chmod +x ./scripts/push.sh
script:
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/push.sh
cache:
  yarn: true
  directories:
    - node_modules
    - /home/travis/.rvm/
notifications:
  email: false
